Organisation Page
alkem-io/client-web pull request #1093
Opened 2021-09-09 16:25 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-09-09 17:38 UTC, techsmyth approved these changes
Nice to have this page there! 

Overall working nicely. Only comment is that I think that what you were first doing, having the owners / admins up in the top section under the tags would be a much better usage of space. The members can be a section below - but as there are in general not likely to be more than 1-2 owners / admins then I think these should go to the top, also so that people know who to connect with. 

But this we can pick up in a future refinement when we can look at the whole page UX.

2021-09-13 09:02 UTC, atstojanov requested changes

2021-09-13 10:16 UTC, techsmyth commented on src/routing/routing.tsx
> +      <Route path="/organisation/:organisationId">
We need a discussion I think on route naming, as I also doubt that we need to have 'challenges' in the main route.

2021-09-13 10:21 UTC, atstojanov commented on src/routing/routing.tsx
> +      <Route path="/organisation/:organisationId">
We need fundamental refactoring of the routing, but for that the UI/UX design update is required.

2021-09-13 15:42 UTC, techsmyth commented on src/routing/routing.tsx
> +      <Route path="/organisation/:organisationId">
I suggest for now just switch to the american version singular i.e. /organization/

2021-09-13 18:46 UTC, atstojanov requested changes

2021-09-13 18:46 UTC, atstojanov commented on src/i18n/en/translation.en.json
> -      "no-tags": "No tags available",
this one is used in `OrganizationPopUp.tsx`

![image](https://user-images.githubusercontent.com/3524687/133139507-36a2e464-ca1d-42e3-b045-d6381860e1e7.png)

2021-09-14 06:29 UTC, atstojanov approved these changes

2021-09-14 06:31 UTC, merged