rg page to allow editing of additional fields and owners
alkem-io/client-web pull request #1097
Opened 2021-09-10 13:58 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-09-11 06:23 UTC, techsmyth approved these changes
Working nicely. It does now send up the nameID as part of the update request, which actually showed up a bug on the server - fixed in https://github.com/alkem-io/server/pull/1362.

2021-09-14 07:18 UTC, atstojanov requested changes

2021-09-14 07:18 UTC, atstojanov commented on src/pages/Admin/Organisation/OrganisationOwnerAuthorizationPage.tsx
> +            onRemove={actions.handleRemoveAdmin}
Should be `handleAssignOwner` and `handleRemoveOwner`

2021-09-14 07:18 UTC, atstojanov commented on src/pages/Admin/Organisation/OrganisationOwnerAuthorizationPage.tsx
> +export const OrganisationOwnerAuthorizationPage: FC<OrganisationAuthorizationPageProps> = ({ paths }) => {
UK->US

2021-09-14 07:18 UTC, atstojanov commented on src/routing/admin/organisation/OrganisationAuthorizationRoute.tsx
> +        <OrganisationOwnerAuthorizationPage paths={currentPaths} />
the `:role` parameter is redundant. The previous part of the path contains the actual role and the parameter is never used.

2021-09-14 07:44 UTC, atstojanov approved these changes

2021-09-14 07:45 UTC, merged