Community page
alkem-io/client-web pull request #1127
Opened 2021-09-17 12:17 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-09-17 15:02 UTC, atstoyanov requested changes

2021-09-17 15:02 UTC, atstoyanov commented on src/utils/urlBuilders.ts
> +const COMMUNITY_ROUTE = '/community';
There is a place for constants: `models/constants`.

2021-09-20 09:24 UTC, hero101 commented on src/context/ChallengeProvider.tsx
> +}
Addressed in [1134](https://github.com/alkem-io/client-web/pull/1134)

2021-09-21 06:37 UTC, atstoyanov approved these changes

2021-09-21 08:57 UTC, atstoyanov approved these changes

2021-09-21 08:57 UTC, merged