Update application logic
alkem-io/client-web pull request #1128
Opened 2021-09-17 14:26 UTC by atstoyanov

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-09-19 06:37 UTC, techsmyth reviewed
First pass at testing has this working nicely.

Realized when testing it that there is one case missing: user clicks apply on a Challenge and they already have an ecoverse application that is pending. In that case the popup should state the text below and then I think bring the user to the Challenge application form:
"To join 'tesats' you must join 'Default Ecoverse' ecoverse first. There is already an application pending for that 'Default Ecoverse", so you can also submit a parallel application for 'tesats'."

2021-09-20 08:07 UTC, techsmyth requested changes
Nice that the logic is there now for the challenge application once the ecoverse applicaiton is pending.

However the challenge does not show "application pending" after submitting the application.

steps:
- apply to join ecoverse
- apply to join child challenge
Apply button should not be still offered as an option to the user.

2021-09-20 09:14 UTC, techsmyth approved these changes
Working nicely now, thanks

2021-09-20 12:52 UTC, hero101 requested changes

2021-09-20 12:52 UTC, hero101 commented on src/components/composite/common/ApplicationButton/ApplicationButton.tsx
> +import { Link } from 'react-router-dom';
rename `Link` to `RouterLink` to avoid any future breaking changes.

2021-09-20 19:51 UTC, hero101 approved these changes

2021-09-20 20:39 UTC, merged