Strongly typed url parameters
alkem-io/client-web pull request #1134
Opened 2021-09-20 09:24 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-09-20 10:51 UTC, hero101 commented
First, [1127](https://github.com/alkem-io/client-web/pull/1127) must be addressed.
After that conflicts need to be resolved and I will rename `id` to `nameId` where needed.

2021-09-21 12:10 UTC, atstoyanov requested changes

2021-09-21 12:10 UTC, atstoyanov commented on src/routing/ulr-params.ts
> +import nameof from '../utils/name-of';
Fix name: `url-params.ts`

2021-09-21 12:20 UTC, atstoyanov approved these changes

2021-09-21 12:20 UTC, merged