More details on pending applications in user profile
alkem-io/client-web pull request #1204
Opened 2021-10-01 09:19 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-10-01 09:20 UTC, hero101 commented
This PR is related to [server PR#1428](https://github.com/alkem-io/server/pull/1428)

2021-10-01 13:54 UTC, atstoyanov requested changes

2021-10-01 13:54 UTC, atstoyanov commented on src/components/UserProfile/application/PendingApplications.tsx
> +const PendingApplications: FC<Props> = ({ user, canEdit = true }) => {
This can be extracted into a container with business logic. Loading data, actions etc. example: `OpportunityMembers`.

2021-10-01 13:54 UTC, atstoyanov commented on src/components/UserProfile/application/PendingApplications.tsx
> +};
Separate presentation and business logic (Loading, actions etc.). Example: `OpportunityMembers`.

Another idea - same thing can be achieved by using hooks #1260 - `useApplicationCommunityQuery`

Can be discussed it more next week.

2021-10-01 13:54 UTC, atstoyanov commented on src/components/UserProfile/application/PendingApplications.tsx
> +};
Move in the utils.

2021-10-05 11:04 UTC, atstoyanov approved these changes

2021-10-05 13:08 UTC, merged