Community Panel: Implement Discussions tab
alkem-io/client-web pull request #1336
Opened 2021-11-10 13:07 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-11-10 23:27 UTC, Comoque1 commented
1. Clicking on "discussion link, redirects to 404 page:
![image](https://user-images.githubusercontent.com/23620658/141207723-a470a76f-5ba1-47c3-8f45-838b10de9b3d.png)
![image](https://user-images.githubusercontent.com/23620658/141207752-44a23c5a-be03-413c-93bb-09677ea47d35.png)

2. Discussions are displayed only on Ecoverse community. For Challenges and Opportunities are missing.
![image](https://user-images.githubusercontent.com/23620658/141209858-153993ec-6a50-4287-bb4e-6c07fffb2936.png)

2021-11-11 11:13 UTC, atstoyanov requested changes

2021-11-11 11:13 UTC, atstoyanov commented on src/routing/discussions/DiscussionsRoute.tsx
> +    <CommunityProvider>
Not needed here. Already provided upper in the tree.

2021-11-11 11:23 UTC, atstoyanov approved these changes

2021-11-11 11:38 UTC, merged