Email Verification page: friendlier message if link expired
alkem-io/client-web pull request #1808
Opened 2022-03-05 16:58 UTC by me-andre

### Describe the background of your pull request

Email Verification page shows a friendlier message if the verification link has expired. The message points to the next action the user has to take in order to get his email verified.

### Additional context

I introduced a map between Kratos message codes and corresponding i18n labels. But we may consider putting Kratos codes in translations directly and using `t.exists()` to check if the mapping exists.

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-03-06 11:37 UTC, me-andre commented on src/components/Authentication/KratosUI.tsx
> +  console.log(ui.messages);
Needs to be removed

2022-03-07 09:55 UTC, hero101 requested changes

2022-03-07 09:55 UTC, hero101 commented on src/components/Authentication/Kratos/messages.ts
> +  (t: T) =>
you can import `getI18n`  and use it directly without the need to be provided here.

2022-03-07 11:47 UTC, me-andre commented
Closed in favor of https://github.com/alkem-io/client-web/pull/1819

2022-03-07 11:47 UTC, closed without merging