Tabbed Hub Settings UI
alkem-io/client-web pull request #1934
Opened 2022-04-05 20:40 UTC by me-andre

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-04-07 06:34 UTC, me-andre commented on src/pages/Admin/Challenge/ChallengeContext/ChallengeContextView.tsx
> +          // nameID: nameID,
TODO remove commented code

2022-04-07 06:35 UTC, me-andre commented on src/routing/admin/challenge/ChallengeRoute.tsx
> +              parentCommunityId={parentCommunityId}
TODO maybe rename back

2022-04-07 06:36 UTC, me-andre commented on src/routing/admin/opportunity/OpportunityRoute.tsx
> +        <Route path={'lifecycle'} element={<OpportunityLifecycleRoute />} />
TODO double quotes

2022-04-08 08:25 UTC, hero101 requested changes
Hard to track what is done in so big PR.
There is obvious refactoring work needed in some views to extract the data fetching and actions, but should be done at another time.
- The Authorization tabs on a Hub, Challenge, and Opportunity are rerendering and it's always clickable, refetching data and refreshing
- Creating Hub redirects to 404.
- Creating Challenge redirects to 404.
- Creating Opportunity redirects to 404.

2022-04-08 08:25 UTC, hero101 commented on src/components/composite/layout/OpportunitySettingsLayout/OpportunitySettingsLayout.tsx
> +        aria-label="Challenge Settings tabs"
opportunity

2022-04-08 14:03 UTC, hero101 approved these changes

2022-04-08 14:07 UTC, merged