You can see who created the aspect in its dashboard
alkem-io/client-web pull request #1993
Opened 2022-04-15 12:40 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-04-15 14:01 UTC, Comoque1 commented
Probably should move First name/Last name above each other, when the text is longer.
![image](https://user-images.githubusercontent.com/23620658/163580035-898aa8fa-1f87-4eee-8e4b-2eae2671aa01.png)

2022-04-18 08:15 UTC, me-andre requested changes

2022-04-18 08:15 UTC, me-andre commented on src/containers/aspect/AspectDashboardContainer/AspectDashboardContainer.tsx
> +  const createdDate = aspect && new Date(aspect.createdDate);
I would avoid to pass rich objects as props if they could be instantiated in the consuming view. If there's absolute need for that, you have to wrap its instantiation in `useMemo()`.

2022-04-18 08:15 UTC, me-andre commented on src/containers/aspect/AspectDashboardContainer/AspectDashboardContainer.tsx
> +  const canReadComments = commentsPrivileges.includes(AuthorizationPrivilege.Read) ?? false;
`includes()` always returns a `boolean`.

2022-04-18 09:04 UTC, me-andre approved these changes

2022-04-18 09:49 UTC, hero101 commented
Closing this because the license does not pass.

2022-04-18 09:49 UTC, closed without merging