4 Tabs layout for Entity pages
alkem-io/client-web pull request #2373
Opened 2022-08-02 15:56 UTC by me-andre

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-08-03 09:57 UTC, hero101 requested changes
- in explore on all entities the description is now shown
![image](https://user-images.githubusercontent.com/7901834/182579828-4956f7c9-fc91-49e0-8242-548907df7282.png)
- opening canvases on challenge/opportunity does not work
- opening an aspect does not show the tabs
- creating a project does not work

2022-08-04 14:36 UTC, Comoque1 commented
In the AC, it is stated, to move context + community + hub statistics to "About" page.
1. Hub 'About' page:
![image](https://user-images.githubusercontent.com/23620658/182873409-88e3d547-80b9-4a6c-81f4-1afa0de147fb.png)
2. Challenge 'About' page:
![image](https://user-images.githubusercontent.com/23620658/182873517-240dfb7f-a807-462e-b7e2-4638de119d59.png)
3. Opportunity 'About' page:
![image](https://user-images.githubusercontent.com/23620658/182873781-8e74c8bb-e21e-4a3f-b20a-6111ff426130.png)

Regarding "Projects" tab on opportunity page, in Sigma, the tab name is changed as well as the content:
![image](https://user-images.githubusercontent.com/23620658/182874127-60d18099-cf51-4f71-b38f-ce8f0c777500.png)

Resources: https://www.figma.com/file/HxG0l93psLUxZUDt8IIini/Redesign-V1

2022-08-08 08:10 UTC, hero101 approved these changes

2022-08-08 10:42 UTC, Comoque1 commented
@me-andre, please revert the dashboard for all entities, as they where, without the context data. (could refer to this URL: https://www.figma.com/file/HxG0l93psLUxZUDt8IIini/Redesign-V1?node-id=0%3A1) 
 - `See all` links on Dashboard / About, are redirecting to 404, instead to respective 'About' tab
 - `See all` links on Dashboard / Aspects, are redirecting to 404, instead to respective 'Explore' tab

2022-08-09 13:49 UTC, merged