#2385 Discussion callout without subscription
alkem-io/client-web pull request #2539
Opened 2022-09-01 18:51 UTC by ccanos

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-09-02 10:44 UTC, hero101 requested changes

2022-09-02 10:44 UTC, hero101 commented on src/containers/aspect/AspectDashboardContainer/AspectDashboardContainer.tsx
> +              fragment: MessageDetailsFragmentDoc,
I think you should keep this change

2022-09-02 10:44 UTC, hero101 commented on src/domain/callout/discussion/DiscussionCallout.graphql
> +fragment DiscussionCallout on Comments {
This is not a Discussion callout. The fragment is on comments to begin with.

2022-09-02 10:44 UTC, hero101 commented on src/domain/callout/useCallouts.ts
> +export type DiscussionCalloutFragmentWithCallout = DiscussionCalloutFragment & { calloutNameId: string };
THis is not a discussion callout and it's not with a callout.

2022-09-02 10:44 UTC, hero101 commented on src/domain/callout/useCallouts.ts
> +    | CalloutTypesWithChildTypes[CalloutType.Discussion]
I think you must change the type to Comments for example.

2022-09-02 10:44 UTC, hero101 commented on src/domain/shared/components/Comments/CommentsComponent.tsx
> +  messages?: Comment[];
`Comment[] | undefined`. Not optional.

2022-09-02 10:44 UTC, hero101 commented on src/domain/shared/components/Comments/CommentsComponent.tsx
> +  commentsId?: string;
`string | undefined`. Not optional.

2022-09-02 10:44 UTC, hero101 commented on src/domain/shared/components/Comments/CommentsComponent.tsx
> +  loading?: boolean;
This is not used.

2022-09-02 10:44 UTC, hero101 commented on src/domain/shared/components/Comments/postComment.graphql
> +mutation PostComment($messageData: CommentsSendMessageInput!) {
this story has nothing to do with aspects.

2022-09-05 15:18 UTC, techsmyth submitted a review, later dismissed
Working fine for me functionally. It may be useful that Svetlo has a look at the code before merging...

2022-09-07 08:55 UTC, hero101 requested changes

2022-09-07 08:55 UTC, hero101 commented on src/domain/callout/comments/CommentsCallout.tsx
> +    [messages, user, isAuthenticated]
that's not the correct deps

2022-09-07 08:55 UTC, hero101 commented on src/domain/callout/comments/CommentsCallout.tsx
> +    update: (cache, { data }) => data?.removeComment && evictFromCache(cache, String(data.removeComment), 'Message'),
any particular reason to use `evictFromCache` instead of `removeFromCache`

2022-09-07 08:55 UTC, hero101 commented on src/domain/callout/comments/CommentsCallout.tsx
> +      const cacheMessageId = cache.identify({
The name is misleading. This is the ID of the cached `Comments` object

2022-09-07 08:55 UTC, hero101 commented on src/domain/callout/creation-dialog/steps/CalloutInfoStep/CalloutForm.tsx
> +      { id: CalloutType.Comments, name: t('common.discussion') },
`common.comments`

2022-09-07 08:55 UTC, hero101 commented on src/domain/callout/creation-dialog/steps/CalloutInfoStep/CalloutForm.tsx
>  import React, { FC, useMemo } from 'react';
I think it should be outside the info step. It is shared between two steps.

2022-09-07 08:55 UTC, hero101 commented on src/domain/shared/components/Comments/commentsDetails.graphql
> +fragment CommentsDetails on Comments {
Rename to `CommentsWithMessages` or something related to be more explicit about the contents. `Details` is vague and prooved inefficient for understanding the codebase.

2022-09-07 13:56 UTC, hero101 submitted a review, later dismissed

2022-09-07 14:36 UTC, hero101 approved these changes

2022-09-07 14:41 UTC, merged