Community Invitations/Pending Memberships
alkem-io/client-web pull request #4316
Opened 2023-07-01 05:55 UTC by me-andre

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2023-07-04 13:22 UTC, ccanos requested changes
A few small changes requested. as we talked most can be ignored if they imply a big refactor

2023-07-04 13:22 UTC, ccanos commented on src/domain/challenge/space/pages/SpaceCommunity/useSpaceCommunityContext.ts
> +  const { data: spaceDisplayNameData } = useSpaceDisplayNameQuery({
Another query just for the displayName sounds excesive to me, isn't there a better way to obtain it or isn't it easy to pass it from higher... in SpaceCommunityPage you have a useSpace which is not nice, but has the profile.

2023-07-04 13:22 UTC, ccanos commented on src/domain/challenge/space/pages/SpaceCommunity/spaceApplicationsInvitations.graphql
> +    visual(type: AVATAR) {
if it's an easy change, I'm trying to do `avatar: visual....`
If you need to refactor something else forget it.

2023-07-04 13:22 UTC, ccanos commented on src/domain/shared/components/RadioButtons/RadioButton.tsx
> +  // width: iconButtonSize,
should we remove these?

2023-07-06 10:34 UTC, ccanos requested changes
a few small changes

2023-07-06 10:34 UTC, ccanos commented on src/domain/community/pendingMembership/PendingMemberships.graphql
> +    profile {
missing id

2023-07-07 14:38 UTC, ccanos requested changes
All good with the code, changes look good to me and you have addressed all my comments, but I have tested it locally and I'm getting this dialog that stays after Accepting an Invitation... 
![image](https://github.com/alkem-io/client-web/assets/16032487/253f8bf5-5aef-4778-acc0-b54943e894f5)

Not sure if I'm doing something wrong, the mutation is returning ok:
![image](https://github.com/alkem-io/client-web/assets/16032487/ba5f5a5e-27c6-4636-b073-b0a5dbaa23f3)
I'm on `develop` branch on the server

2023-07-10 06:54 UTC, ccanos approved these changes

2023-07-10 11:09 UTC, valentinyanakiev approved these changes

2023-07-10 11:09 UTC, merged