Client Code Guidelines put into docs
alkem-io/client-web pull request #4521
Opened 2023-08-10 06:19 UTC by me-andre

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2023-08-10 16:58 UTC, techsmyth commented
@me-andre Nice set of guidelines. 

There are a few other points I would like to discuss: 
- Usage of models to isolate from grapgql type changes: we should in general be minimizing the direct usage of types from the generated graphql
- Only lookup based on uuid, not nameid: I picked up before that callouts are looking up based on NameID, which is not supported via lookups so the client should not be using nameID to find a particular child
- Directory structure  in domain: we need a review of the structure being used within src/domain. This has some strange nesting e.g. around templates / innovation library. Templates exist independently of Innovation Library.

Looking forward to discussing more.

2023-08-16 11:32 UTC, ccanos requested changes

2023-08-16 11:32 UTC, ccanos commented on docs/code-guidelines.md
> +## To be done:
I would like to have some kind of summary of all of this to take a look during CodeReviews, like a list of checks or something like that.
I guess somebody else can do it, probably myself :D

2023-08-16 11:35 UTC, ccanos commented on docs/code-guidelines.md
> +> :warning: All code built for Admin side should go under `src/platform/admin`.
you mentioned in your comment, " Admin prefix for admin-side pages, views and containers". I didn't see that clearly in the document

2023-08-18 10:03 UTC, ccanos approved these changes

2023-08-18 10:04 UTC, ccanos commented
closed to retrigger CLA

2023-08-18 10:59 UTC, valentinyanakiev approved these changes

2023-08-18 10:59 UTC, merged