Router information and tags added to Sentry error logging
alkem-io/client-web pull request #5847
Opened 2024-04-01 09:08 UTC by bobbykolev

### Describe the background of your pull request
As part of the client's observability initiative, this PR aims to add additional information to our error logs.

### Changes
Route information was added on Sentry init. 
The Sentry error logs now support passing tags. 

I suggest keeping the tags (at least the keys) strictly defined, but more flexibility is possible.
The tags could be easily added to the other types of logs (warning, info, etc) but we don't use them ATM.

2024-04-09 11:34 UTC, hero101 requested changes

2024-04-09 11:34 UTC, hero101 commented on src/core/logging/sentry/log.ts
> +    for (const [key, value] of Object.entries(tags as TagType)) {
is type casting needed when we know **tags** is already defined?

2024-04-09 11:34 UTC, hero101 commented on src/core/logging/sentry/log.ts
> +const setTags = (tags: TagType | undefined, scope: Sentry.Scope) => {
i think it makes more sense the mandatory parameters to be first. Also it doesnt make sense to set tags when there are no tags provided.

2024-04-11 06:17 UTC, hero101 approved these changes

2024-04-11 06:17 UTC, hero101 approved these changes

2024-04-11 06:17 UTC, merged

2024-04-11 06:59 UTC, bobbykolev commented on src/core/logging/sentry/log.ts
> +export const tagCategoryValues = {
Sure I'll switch to Enum in the next PR, thanks!

2024-04-11 07:01 UTC, bobbykolev commented on src/core/logging/sentry/log.ts
> +  LABEL: 'LABEL',
I prefer to keep them uppercase as constants and easy to spot as such on Sentry.