Add preview dialog for Member guidelines templates
alkem-io/client-web pull request #6160
Opened 2024-05-09 14:32 UTC by EmiliaPavlova

- Add preview dialog for Member guidelines templates
- Fix preview dialog for Callout templates

Depends on [#5924](https://github.com/alkem-io/client-web/pull/6150)

2024-05-09 16:06 UTC, EmiliaPavlova commented on src/domain/collaboration/memberGuidelines/MemberGuidelinesTemplateLibrary/MemberGuidelinesTemplatePreview.tsx
> +        {t('components.callout-creation.template-step.post-template-default-description')}
TODO: update translation

2024-05-13 15:33 UTC, ccanos requested changes

2024-05-13 15:33 UTC, ccanos commented on src/domain/community/community/CommunityGuidelines/CommunityGuidelines.tsx
> +        console.log(values);
please remove this console.log

2024-05-14 06:35 UTC, EmiliaPavlova commented on src/domain/community/community/CommunityGuidelines/CommunityGuidelines.tsx
> +        console.log(values);
Removed

2024-05-14 06:35 UTC, EmiliaPavlova commented on src/domain/collaboration/communityGuidelines/CommunityGuidelinesTemplateLibrary/CommunityGuidelinesTemplatePreview.tsx
> +      {/* <ProfileReferenceSegment references={mockValues.references} profileId={"data?.profile?.id"} /> */}
The server is not ready, there are no references yet.

2024-05-14 10:05 UTC, ccanos approved these changes

2024-05-14 10:06 UTC, merged