Add Allow admin support option in Settings tab and remove magic url in Community tab
alkem-io/client-web pull request #6216
Opened 2024-05-21 13:49 UTC by EmiliaPavlova

- In Space Settings > Settings, in the Member Actions add switch for Alkemio Support at the bottom, below the switch from [#6200](https://github.com/alkem-io/client-web/issues/6200)
- In Community Settings remove Copy Magic URL button from Invite others block

2024-05-21 15:17 UTC, ccanos approved these changes
I think the changes are good, but they are not building. 
It's because of these changes https://github.com/alkem-io/server/pull/3948 we need to ask tomorrow about them

2024-05-21 17:02 UTC, techsmyth commented
@ccanos @EmiliaPavlova it may be that this PR fixes it: https://github.com/alkem-io/server/pull/3965

2024-05-21 21:08 UTC, bobbykolev submitted a review, later dismissed

2024-05-22 06:36 UTC, ccanos requested changes
@EmiliaPavlova  I have merged https://github.com/alkem-io/server/pull/3965 to develop, please pull latest server, run codegen and push it, that should fix the build error

2024-05-22 06:52 UTC, ccanos approved these changes

2024-05-22 06:52 UTC, merged