Fix - 404 for callouts preview dialog in innovation library
alkem-io/client-web pull request #6358
Opened 2024-06-07 14:27 UTC by bobbykolev

https://github.com/alkem-io/client-web/issues/6353

2024-06-07 16:35 UTC, ccanos requested changes

2024-06-07 16:35 UTC, ccanos commented on src/domain/platform/admin/templates/InnovationPacks/admin/AdminInnovationPackPage.tsx
> +    calloutTemplateId,
you need to add this to `src/main/routing/urlParams.ts`

2024-06-10 08:04 UTC, ccanos approved these changes

2024-06-10 12:20 UTC, valentinyanakiev approved these changes

2024-06-10 12:52 UTC, merged