Create VC flow
alkem-io/client-web pull request #6679
Opened 2024-07-29 14:45 UTC by EmiliaPavlova

When a user clicks on the Create VC button, open dialog with:

1.  VC profile info

- Name (required)
- (Avatar - in future task)
- Tagline
- Description

2.  Three choices for what the user wants to make available through their VC:

- Written knowledge: [#6603](https://github.com/alkem-io/client-web/issues/6603)
- Content of a (sub)space [#6604](https://github.com/alkem-io/client-web/issues/6604)
- External AI [#6605](https://github.com/alkem-io/client-web/issues/6605)

3.  Create button

2024-08-07 09:50 UTC, ccanos requested changes
please take a look at these comments

2024-08-07 09:50 UTC, ccanos commented on src/main/topLevelPages/myDashboard/newVirtualContributorWizard/newVirtualContributorQueries.graphql
> +      community {
community is repeated here

2024-08-07 09:50 UTC, ccanos commented on src/main/topLevelPages/myDashboard/newVirtualContributorWizard/newVirtualContributorQueries.graphql
> +query NewSpace($spaceId: UUID_NAMEID!) {
I'd call this `SpaceUrl`, and maybe there's already a similar query. 
Also if we have the ID (which I'm pretty sure we do), better access it through the lookup with UUID. if not please call the parameter $spaceNameId

2024-08-07 09:50 UTC, ccanos commented on src/main/topLevelPages/myDashboard/newVirtualContributorWizard/LoadingState.tsx
> +      <Gutters padding={gutters(2)} sx={{ textAlign: 'center' }}>
I think `textAlign` is a property of `BoxProps` and can be used directly outside `sx`

2024-08-07 14:47 UTC, bobbykolev approved these changes

2024-08-08 11:24 UTC, bobbykolev approved these changes

2024-08-08 15:08 UTC, bobbykolev approved these changes

2024-08-08 15:11 UTC, ccanos approved these changes

2024-08-08 15:20 UTC, merged