Administration UI for selecting the organisations that are leads on a challenge
alkem-io/client-web pull request #833
Opened 2021-07-14 13:26 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-07-14 13:44 UTC, techsmyth approved these changes
Working nicely! Exactly what I think we needed...

2021-07-14 13:58 UTC, hero101 commented on src/components/Admin/Community/LeadingOrganisationPage.tsx
> +interface Type {
This type must be the same as the return type of the query - here I am using a substitue type.
How can this be achieved @atstojanov ?

2021-07-14 15:15 UTC, atstojanov requested changes

2021-07-14 15:15 UTC, atstojanov commented on graphql/queries/challengeLeadOrganisations.graphql
> +}
Both queries can be combined in single one to serve exactly this page. Also the whole object for the leadOrganisations can be loaded, which can be used directly as Leading organizations and just filter out the reset. Also the organizations fields can be defined as a fragment which will resolve the type question.

2021-07-16 06:39 UTC, atstojanov approved these changes

2021-07-16 06:39 UTC, merged